#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

STORE="apps/watchos/AgentPulseWatch/AgentPulseWatch/AgentPulseStore.swift"
PREVIEW_SCRIPT="scripts/verify/run_watch_ultra_simulator_preview.sh"
PLAN="docs/exec-plans/active/watch-ultra-simulator-preview.md"

test -f "$STORE"
test -f "$PREVIEW_SCRIPT"
test -f "$PLAN"

grep -q "AGENT_PULSE_WATCH_PREVIEW_FIXTURE" "$STORE"
grep -q "AGENT_PULSE_WATCH_PREVIEW_STATE" "$STORE"
grep -q "SimulatorPreviewState" "$STORE"
grep -q "makeSimulatorPreviewSummary" "$STORE"
grep -q "makeSimulatorPreviewAttention" "$STORE"
grep -q "makeSimulatorPreviewTranscript" "$STORE"
grep -q "https://beta.dope-ai.kr/agent-pulse" "$STORE"
grep -q "Open on Mac is disabled" "$STORE"
grep -q "case pairing" "$STORE"
grep -q "case detailMessages" "$STORE"
grep -q "case detailActions" "$STORE"
grep -q "case attentionDetail" "$STORE"
grep -q "case attentionActions" "$STORE"
grep -q "case revoked" "$STORE"

grep -q "Apple Watch Ultra 3 (49mm)" "$PREVIEW_SCRIPT"
grep -q "Apple Watch Ultra 2 (49mm)" "$PREVIEW_SCRIPT"
grep -q "Apple Watch Ultra (49mm)" "$PREVIEW_SCRIPT"
grep -q "CODE_SIGNING_ALLOWED=NO" "$PREVIEW_SCRIPT"
grep -q "AGENT_PULSE_WATCH_PREVIEW_FIXTURE" "$PREVIEW_SCRIPT"
grep -q "summary.png" "$PREVIEW_SCRIPT"
grep -q "attention.png" "$PREVIEW_SCRIPT"
grep -q "attention-detail.png" "$PREVIEW_SCRIPT"
grep -q "attention-detail-actions.png" "$PREVIEW_SCRIPT"
grep -q "start-thread.png" "$PREVIEW_SCRIPT"
grep -q "thread-detail.png" "$PREVIEW_SCRIPT"
grep -q "thread-detail-messages.png" "$PREVIEW_SCRIPT"
grep -q "thread-detail-actions.png" "$PREVIEW_SCRIPT"
grep -q "revoked.png" "$PREVIEW_SCRIPT"
grep -q "summary-simulator-window.png" "$PREVIEW_SCRIPT"
grep -q "attention-simulator-window.png" "$PREVIEW_SCRIPT"
grep -q "attention-detail-simulator-window.png" "$PREVIEW_SCRIPT"
grep -q "attention-detail-actions-simulator-window.png" "$PREVIEW_SCRIPT"
grep -q "start-thread-simulator-window.png" "$PREVIEW_SCRIPT"
grep -q "thread-detail-simulator-window.png" "$PREVIEW_SCRIPT"
grep -q "thread-detail-messages-simulator-window.png" "$PREVIEW_SCRIPT"
grep -q "thread-detail-actions-simulator-window.png" "$PREVIEW_SCRIPT"
grep -q "revoked-simulator-window.png" "$PREVIEW_SCRIPT"
grep -q "screencapture" "$PREVIEW_SCRIPT"
grep -q "Simulator window/body" "$PREVIEW_SCRIPT"
grep -q "Apple Watch Ultra-family raw screenshot" "$PREVIEW_SCRIPT"

grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/summary.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/attention.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/attention-detail.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/attention-detail-actions.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/start-thread.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/thread-detail.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/thread-detail-messages.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/thread-detail-actions.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/summary-simulator-window.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/attention-simulator-window.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/attention-detail-simulator-window.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/attention-detail-actions-simulator-window.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/start-thread-simulator-window.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/thread-detail-simulator-window.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/thread-detail-messages-simulator-window.png" "$PLAN"
grep -q "retain-artifact: docs/exec-plans/active/watch-ultra-simulator-preview-screenshots/thread-detail-actions-simulator-window.png" "$PLAN"

echo "Agent Pulse Watch Ultra simulator preview contract passed"
